name: xt_router
description: Simple and powerful router for Flutter
version: 0.1.0
homepage: https://github.com/xork-tech/xt_router.git

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: