name: xt_router
description: xt_router a powerful library implementing a Navigator 2.0. The router provides efficient routing capabilities, allowing you to handle complex navigation flows effortlessly.
version: 0.5.0
homepage: https://github.com/xork-tech/xt_router.git

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: